package com.adityavikas.codeverse.entity;

import jakarta.validation.constraints.NotNull;
import lombok.Data;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

@Data
@Document(collection = "Submission")
public class Submission {

    @Id
    private ObjectId submissionId;

    @Indexed(unique = true)
    private String username;

    private ObjectId problemId;

    private String userCode;
    private String language;
    private LocalDateTime submittedAt;   // generate by LocalDateTime.now()
    private String status;   //ACCEPTED,Time Limit Exceeded,Wrong Answer,Runtime Error
    private Double time;    //generated by system
    private Double memory;  //generated by system
    @NotNull
    private String slug;   //generate by UUID library

}
