spring.data.mongodb.uri=${MONGODB_URI}
google.auth.redirect_uri=${REDIRECT_URI}
google.auth.client_id=${CLIENT_ID}
google.auth.client_secret=${CLIENT_SECRET}
cloud.cloud-name=${cloud_name}
cloud.api-key=${cloudinary_api_key}
cloud.api-secret=${cloudinary_api_secret}