spring.application.name=codeverse
spring.data.mongodb.uri=mongodb+srv://springboot_aditya:UiuGWCph6hmE4qE5@cluster0.atr8mdg.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=codeversedb
spring.data.mongodb.auto-index-creation=true